"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-05-26 17:08:45.376528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('strategy', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('sent_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_msg_id', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_retry_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending','sent','failed','dropped')", name='ck_alerts_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_ts'), 'alerts', ['ts'], unique=False)
    op.create_index(
        op.f("ix_alerts_symbol_strategy"),
        "alerts",
        ["symbol", "strategy"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alerts_status_next_retry_ts"),
        "alerts",
        ["status", "next_retry_ts"],
        unique=False,
    )
    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tickers_scanned', sa.Integer(), nullable=True),
    sa.Column('alerts_fired', sa.Integer(), nullable=True),
    sa.Column('errors_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spot', sa.Float(), nullable=True),
    sa.Column('iv_rank', sa.Float(), nullable=True),
    sa.Column('hv20', sa.Float(), nullable=True),
    sa.Column('iv_hv_ratio', sa.Float(), nullable=True),
    sa.Column('expected_move', sa.Float(), nullable=True),
    sa.Column('regime_dir', sa.Text(), nullable=True),
    sa.Column('regime_iv', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.CheckConstraint(
        "regime_dir IN ('bull','neutral','bear') OR regime_dir IS NULL",
        name=op.f('ck_snapshots_regime_dir'),
    ),
    sa.CheckConstraint(
        "regime_iv IN ('high','neutral','low') OR regime_iv IS NULL",
        name=op.f('ck_snapshots_regime_iv'),
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_symbol'), 'snapshots', ['symbol'], unique=False)
    op.create_index(op.f('ix_snapshots_ts'), 'snapshots', ['ts'], unique=False)
    op.create_table('watchlist',
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('view_override_dir', sa.Text(), nullable=True),
    sa.Column('view_override_iv', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint(
        "view_override_dir IN ('bull','neutral','bear') OR view_override_dir IS NULL",
        name=op.f('ck_watchlist_view_override_dir'),
    ),
    sa.CheckConstraint(
        "view_override_iv IN ('high','neutral','low') OR view_override_iv IS NULL",
        name=op.f('ck_watchlist_view_override_iv'),
    ),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('strategy_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('legs_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_scores_snapshot_id'), 'strategy_scores', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_strategy_scores_strategy'), 'strategy_scores', ['strategy'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_scores_strategy'), table_name='strategy_scores')
    op.drop_index(op.f('ix_strategy_scores_snapshot_id'), table_name='strategy_scores')
    op.drop_table('strategy_scores')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_snapshots_ts'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_symbol'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_table('scan_runs')
    op.drop_index(op.f("ix_alerts_status_next_retry_ts"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_symbol_strategy"), table_name="alerts")
    op.drop_index(op.f('ix_alerts_ts'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
